### ISSUE TITLE
Members page improvements

### ISSUE THREAD

**Issue by fmdkdd** [NaoMod/naomod.github.io#2]
- [x] Add pictures for everyone
- [x] Add links from names to these individual's pages
- [x] Add affiliations for each member

Decisions to be taken:
1. ~~Do we want to include past members from Atlanmod?~~ I added former Naomod members, it seemed only fair.
2. ~~Do we add affiliations under the position (Univ Nantes, IUT, etc.)?~~ Yes.

**Comment by Hugo-Bruneliere** [comment]
You can reuse my picture from http://web.emn.fr/x-info/atlanmod/index.php?title=User:Bruneliere
I also have it in higher resolution if needed.
Btw, we could also add links (on the names) to the individual pages/sites.

I guess we should put the affiliations as we are a multi-institution team.
