### ISSUE TITLE
Unify CSS declarations

### ISSUE THREAD

**Issue by ebousse** [NaoMod/naomod.github.io#24]
Currently there are CSS rules spread out in many different files, directly embedded in the HTML code. While this can make sense for very local styles, that only apply to a single page, it is a problem for it is a re-styling of core HTML types (eg. `h2`), as this breaks the visual consistency of the website.

A solution would be to merge at least all CSS rules related to common types of elements in the code CSS file of the site.

**Comment by JolanPhilippe** [comment]
Page-related styles remain defined on each file. Otherwise, all headers, html5-related tags, etc. are defined in a unified style.css file.
