### ISSUE TITLE
Project page improvement

### ISSUE THREAD

**Issue by fmdkdd** [NaoMod/naomod.github.io#3]
Decisions to be taken:

1. Do we want a projects page?
1. What projects do we want to cite here?
2. Do we want just a link per project or a paragraph of description?

**Comment by Hugo-Bruneliere** [comment]
1. Yes I think we should, and this time we should keep it up-to-date :-)
2. We should cite all the ongoing ones, and maybe also the major past ones.
3. Ideally both.

**Comment by fmdkdd** [comment]
Closed by 3b85a6831f161b6718c8f5260e77f37e41fcda10.  Now go add more projects!
